
name: C/C++ CI 

on: [push]

jobs:
  build-logging-interface:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:    
        submodules: recursive

    - name: Install dependencies
      run: sudo apt install -y meson
    
    - name: logging-interface build
      run: meson build logging-interface
    
    - name: Compile projects
      run: ninja -C build

    - name: Run tests
      run: ninja -C build test

